using '../main.bicep'

param location = 'brazilsouth'
param environment = 'dev'
param suffix = 'rpc2026dev'
param storageName = 'stedufeedbackrpc2026dev'
param workspaceName = 'log-edufeedback-dev'
param appInsightsName = 'appi-edufeedback-dev'
param keyVaultName = 'kv-edufeedback-rpc2026dev'
param postgresName = 'pg-edufeedback-rpc2026dev'
param databaseName = 'edufeedbackdb'
param databaseAdmin = 'edufeedbackadmin'
param communicationName = 'acs-edufeedback-rpc2026dev'
param emailServiceName = 'ecs-edufeedback-rpc2026dev'
param functionPlanName = 'plan-edufeedback-dev'
param httpFunctionName = 'func-edufeedback-http-rpc2026dev'
param notificationFunctionName = 'func-edufeedback-notification-rpc2026dev'
param reportFunctionName = 'func-edufeedback-report-rpc2026dev'
// databaseAdminPassword e adminEmail são fornecidos externamente.
