using '../main.bicep'

param location = 'brazilsouth'
param environment = 'prod'
param suffix = 'rpc2026'
param storageName = 'stedufeedbackrpc2026'
param workspaceName = 'log-edufeedback-prod'
param appInsightsName = 'appi-edufeedback-prod'
param keyVaultName = 'kv-edufeedback-rpc2026'
param postgresName = 'pg-edufeedback-rpc2026'
param databaseName = 'edufeedbackdb'
param databaseAdmin = 'edufeedbackadmin'
param communicationName = 'acs-edufeedback-rpc2026'
param emailServiceName = 'ecs-edufeedback-rpc2026'
param functionPlanName = 'plan-edufeedback-prod'
param httpFunctionName = 'func-edufeedback-http-rpc2026'
param notificationFunctionName = 'func-edufeedback-notification-rpc2026'
param reportFunctionName = 'func-edufeedback-report-rpc2026'
// databaseAdminPassword e adminEmail são fornecidos pelo script/pipeline; nunca versionados.
